##############################################################
# Practica Intermedia
##############################################################

@host = http://localhost:3000

### Registro de usuario
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "12345678"
}

### Validar email del usuario
POST {{host}}/api/auth/validate-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWU1ZDg1NjFlZDQ3YjhkZGQwMWM2OCIsImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM2NzQ3NTgsImV4cCI6MTc0NDI3OTU1OH0.FV1z-oVFg2LLM4GHlfhINanpvtaFAl9CDsoxP71LtFU

{
  "code": "386208"
}

### Login de usuario
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "12345678"
}

###
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWU1ZDg1NjFlZDQ3YjhkZGQwMWM2OCIsImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM2NzQ4NDcsImV4cCI6MTc0NDI3OTY0N30.WH3BJH3B9Vl9vrWROhQntpdPPsWyzIa4iENVensSv6I

### Onboarding - Datos personales
PUT {{host}}/api/users/onboarding/personal
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Julian",
  "lastname": "Villar",
  "nif": "12345678H"
}

### Onboarding - Datos compañía
PATCH {{host}}/api/users/onboarding/company
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Mi Empresa S.L.",
  "cif": "B12345678",
  "address": "Calle Ejemplo 123",
  "isAutonomous": false
}

### Upload de logo con form-data
PATCH {{host}}/api/users/logo
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./../uploads/logos/logo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### GET usuario actual
GET {{host}}/api/users/me
Authorization: {{token}}

### DELETE usuario (soft delete)
DELETE {{host}}/api/users
Authorization: {{token}}

### DELETE usuario (hard delete)
DELETE {{host}}/api/users?soft=false
Authorization: {{token}}

##############################################################
# Practica Intermedia
##############################################################

@host1 = http://localhost:3000

# Clientes

### CREAR cliente
POST {{host1}}/api/clients
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Cliente S.A.",
  "cif": "B99999999",
  "address": "Calle Cliente 123",
  "email": "cliente@empresa.com",
  "phone": "600123123"
}

###
@idcliente =  67ee5f3a61ed47b8ddd01c78

### OBTENER todos los clientes (no archivados)
GET {{host1}}/api/clients
Authorization: {{token}}

### OBTENER cliente por ID
GET {{host1}}/api/clients/{{idcliente}}
Authorization: {{token}}

### ACTUALIZAR cliente
PUT {{host1}}/api/clients/{{idcliente}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Cliente Editado S.A.",
  "email": "editado@empresa.com"
}

### ARCHIVAR cliente
PATCH {{host1}}/api/clients/{{idcliente}}/archive
Authorization: {{token}}

### RECUPERAR cliente archivado
PATCH {{host1}}/api/clients/{{idcliente}}/recover
Authorization: {{token}}

### ELIMINAR cliente definitivamente
DELETE {{host1}}/api/clients/{{idcliente}}
Authorization: {{token}}

# Proyectos

### CREAR proyecto
POST {{host}}/api/projects
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Proyecto Inicial",
  "description": "Este es un proyecto de prueba",
  "client": "{{idcliente}}"
}

###
@projectId =  67ee65db55efea8785dc039d

### OBTENER todos los proyectos del usuario
GET {{host}}/api/projects
Authorization: {{token}}

### OBTENER un proyecto por ID
GET {{host}}/api/projects/{{projectId}}
Authorization: {{token}}

### ACTUALIZAR proyecto
PUT {{host}}/api/projects/{{projectId}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Proyecto Actualizado",
  "description": "Descripción actualizada del proyecto"
}

### ARCHIVAR proyecto
PATCH {{host}}/api/projects/{{projectId}}/archive
Authorization: {{token}}

### RECUPERAR proyecto archivado
PATCH {{host}}/api/projects/{{projectId}}/recover
Authorization: {{token}}

### ELIMINAR proyecto permanentemente
DELETE {{host}}/api/projects/{{projectId}}
Authorization: {{token}}